name: Run Jest Tests

on:
  pull_request:
    branches:
      - main
timeout-minutes: 3
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Using Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Give GitHub Actions access to Oyl-Sdk
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.OYL_TEST_ACCESS }}
      - name: Install dependencies
        run: npm install
      - name: unit test
        run: npm run test
